In [1]:
#import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import os
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Ready_FS.csv")
first_col = df.pop("Genome")
df.insert(0, "Genome", first_col)
df[["Metadata_field"]].to_csv("labels.tsv", header=None, index=False)
df[["Genome","Metadata_field"]].to_csv("Metadata.csv", header=None, index=False)

df = df.drop(columns="Metadata_field")
df.head()
#df.to_csv("Ready_noheader.csv", index=False, header=None)

,Genome,PF10417.10,PF00389.31,PF02826.20,PF00198.24,PF16078.6,PF05635.12,PF03171.21,PF13532.7,PF13640.7,...,PF00201.19,PF07686.18,PF05406.16,PF11846.9,PF01797.17,PF08803.12,PF14588.7,PF11706.9,PF04354.14,PF16916.6
0,Aq_sp_Aq107,1,5,11,4,1,2,1,1,3,...,0,0,0,0,0,0,0,0,0,0
1,Aq_sp_Aq135,2,3,7,4,1,1,1,1,2,...,0,0,0,0,0,0,0,0,0,0
2,Aq_sp_Aq349,3,3,8,4,1,1,1,1,2,...,1,1,3,1,1,2,1,1,1,1
3,GCA_002714325.1_ASM271432v1,1,2,3,3,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,GCA_002714325.1_ASM271432v1_genomic,1,2,3,3,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df.iloc[:,:300].to_csv("1.csv")

In [4]:
df.iloc[:,300:600].to_csv("2.csv")